name: reada
description: "Reada mobile application"
publish_to: 'none' 
version: 1.0.7+7

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it: ^8.0.3
  http: ^1.3.0
  logger: ^2.6.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  firebase_core: ^3.11.0
  pinput: ^5.0.1
  toastification: ^3.0.3
  flutter_svg: ^2.2.0
  equatable: ^2.0.7
  intl_phone_field: ^3.2.0
  intl: ^0.20.2
  collection: ^1.19.1
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

